route:
  receiver: 'slack'

receivers:
  - name: 'slack'
    slack_configs:
        - send_resolved: true
          text: "{{ .CommonAnnotations.description }}"
          username: 'Prometheus'
          channel: '#bechdel-lists'
          api_url: 'https://hooks.slack.com/services/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'
