version: '3'
services:
  prometheus:
    image: prom/prometheus:v2.18.1
    container_name: prometheus
    ports:
      - 9090:9090
    command:
        - --config.file=/etc/prometheus/prometheus.yml
        - --web.external-url=https://monitoring.jbrunton.com/prometheus/
        - --web.route-prefix=/prometheus/
    volumes:
      - $PROMETHEUS_DIR:/etc/prometheus
      - $DATA_DIR/prometheus:/prometheus
  grafana:
    image: grafana/grafana:7.0.0
    container_name: grafana
    ports:
      - 3000:3000
    depends_on:
      - prometheus
    volumes:
      - $GRAFANA_DIR/grafana.ini:/etc/grafana/grafana.ini
      - $GRAFANA_DIR/provisioning:/etc/grafana/provisioning/
      - $DATA_DIR/grafana:/var/lib/grafana
  ping:
    image: "jbrunton/monitoring.jbrunton.com-ping:latest"
    build:
      context: ./ping
    environment:
      - PING_TARGET_HOST
  nginx:
    image: "nginx:1.18.0-alpine"
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - $NGINX_CERTS_DIR:/etc/nginx/certs
      - $NGINX_DIR/default.conf:/etc/nginx/conf.d/default.conf:ro
      - $NGINX_DIR/html:/usr/share/nginx/html:ro
    depends_on:
      - grafana
      - prometheus
