version: '3'
services:
  prometheus:
    image: prom/prometheus:v2.18.1
    container_name: prometheus
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.external-url=https://monitoring.jbrunton.com/prometheus/
      - --web.route-prefix=/prometheus/
    volumes:
      - $PROMETHEUS_DIR:/etc/prometheus
      - $DATA_DIR/prometheus:/prometheus
    depends_on:
      - alertmanager
  alertmanager:
    image: prom/alertmanager:v0.20.0
    container_name: alertmanager
    volumes:
      - $ALERTMANAGER_DIR:/etc/alertmanager
      - $DATA_DIR/alertmanager:/alertmanager
    command:
      - --config.file=/etc/alertmanager/config.yml
      - --web.external-url=https://monitoring.jbrunton.com/alertmanager/
      - --web.route-prefix=/
      - --storage.path=/alertmanager
    restart: unless-stopped
    ports:
      - 9093:9093
  grafana:
    image: grafana/grafana:7.0.0
    container_name: grafana
    ports:
      - 3000:3000
    depends_on:
      - prometheus
    volumes:
      - $GRAFANA_DIR/grafana.ini:/etc/grafana/grafana.ini
      - $GRAFANA_DIR/provisioning:/etc/grafana/provisioning/
      - $DATA_DIR/grafana:/var/lib/grafana
  ping:
    image: "jbrunton/monitoring.jbrunton.com-ping:latest"
    build:
      context: ./ping
  nginx:
    image: "nginx:1.18.0-alpine"
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - $NGINX_CERTS_DIR:/etc/nginx/certs
      - $NGINX_DIR/upstreams.conf:/etc/nginx/upstreams.conf:ro
      - $NGINX_DIR/services.conf:/etc/nginx/services.conf:ro
      - $NGINX_DIR/default.production.conf:/etc/nginx/conf.d/default.conf:ro
      - $NGINX_DIR/html:/usr/share/nginx/html:ro
    depends_on:
      - grafana
      - prometheus
