apiVersion: v1
kind: Service
metadata:
  name: prometheus-node-port
spec:
  type: NodePort
  ports:
    - name: prometheus
      port: 9090
      targetPort: 9090
      nodePort: 31010
  selector:
    component: prometheus
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-node-port
spec:
  type: NodePort
  ports:
    - name: grafana
      port: 3000
      targetPort: 3000
      nodePort: 31000
  selector:
    component: grafana
---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager-node-port
spec:
  type: NodePort
  ports:
    - name: alertmanager
      port: 9093
      targetPort: 9093
      nodePort: 31020
  selector:
    component: alertmanager
    