apiVersion: v1
kind: Service
metadata:
  name: client-node-port
spec:
  type: NodePort
  ports:
    - name: grafana
      port: 3000
      targetPort: 3000
      nodePort: 31000
    - name: prometheus
      port: 9090
      targetPort: 9090
      nodePort: 31010
  selector:
    component: monitoring
