apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoring-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: monitoring
  template:
    metadata:
      labels:
        component: monitoring
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:v2.18.1
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: prometheus-config
              mountPath: /etc/prometheus/prometheus.yml
              subPath: prometheus.yml
        - name: grafana
          image: grafana/grafana:7.0.0
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: grafana-config
              mountPath: /etc/grafana/grafana.ini
              subPath: grafana.dev.ini
            - name: grafana-datasources
              mountPath: /etc/grafana/provisioning/datasources
            - name: grafana-dashboards
              mountPath: /etc/grafana/provisioning/dashboards
      volumes:
        - name: prometheus-config
          configMap:
            name: prometheus-configmap
        - name: grafana-config
          configMap:
            name: grafana-configmap
        - name: grafana-datasources
          configMap:
            name: grafana-datasources-configmap
        - name: grafana-dashboards
          configMap:
            name: grafana-dashboards-configmap
      