apiVersion: v1
kind: Pod
metadata:
  name: monitoring-pod
  labels:
    component: monitoring
spec:
  containers:
    - name: prometheus
      image: prom/prometheus:v2.18.1
      ports:
        - containerPort: 9090
