{
 "title": "Apps Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "instance", "query": "up" }
  ]
 },
 "panels": [
  {
   "title": "API Throughput",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "http:throughput:mean1m{instance=~\"$instance\"}\n",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "API Latency",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "http:latency:mean1m{instance=~\"$instance\"}",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Nginx Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nginx:throughput:mean1m{instance=~\"$instance\"}",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "API Error Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "http:errors:mean1m", "legendFormat": "{{ path }}" }
   ]
  }
 ]
}