resources:
  - ./client-node-port.yml
  - ./monitoring-grafana.yml
  - ./monitoring-prometheus.yml
  - ./monitoring-alertmanager.yml
  - ./monitoring-ingress.yml
configMapGenerator:
  - name: prometheus-configmap
    files:
      - ./prometheus/prometheus.yml
      - ./prometheus/rules.yml
      - ./prometheus/alerts.yml
  - name: grafana-datasources-configmap
    files:
      - ./grafana/provisioning/datasources/prometheus.yml
  - name: grafana-dashboards-configmap
    files:
      - ./grafana/provisioning/dashboards/dashboards.yml
      - ./grafana/provisioning/dashboards/docker-host.json
      - ./grafana/provisioning/dashboards/apps-dashboard.json
secretGenerator:
  - name: alertmanager-config
    files:
      - ./alertmanager/config.yml
