name: deploy

on:
  push:
    branches:
      - master

env:
  CI: 1
  FORCE_COLOR: 1

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: docker login
        env:
          DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}
          DOCKER_USERNAME: jbrunton
        run: echo "$DOCKER_ACCESS_TOKEN" | docker login -u "$DOCKER_USERNAME" --password-stdin
  
      - name: build
        run: |
          docker-compose build
          docker-compose push

      - name: copy files
        uses: appleboy/scp-action@master
        env:
          HOST: monitoring.jbrunton.com
          USERNAME: deployer
          KEY: ${{ secrets.DEPLOYER_SSH_KEY }}
        with:
          source: "docker-compose.yml,.env,prometheus,grafana"
          overwrite: true
          target: .

      - name: deploy
        uses: appleboy/ssh-action@master
        env:
          HOST: monitoring.jbrunton.com
          USERNAME: deployer
          KEY: ${{ secrets.DEPLOYER_SSH_KEY }}
        with:
          script: |
            mkdir -p ping
            docker-compose pull
            docker-compose up --detach --no-build --remove-orphans
