name: deploy

on:
  push:
    branches:
      - master

env:
  CI: 1
  FORCE_COLOR: 1

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: copy files
        uses: appleboy/scp-action@master
        env:
          HOST: ${{ steps.deployment_info.outputs.host }}
          USERNAME: deployer
          KEY: ${{ secrets.DEPLOYER_SSH_KEY }}
        with:
          source: "docker-compose.yml,.env,prometheus,grafana"
          overwrite: true
          target: .

      - name: deploy
        uses: appleboy/ssh-action@master
        env:
          HOST: monitoring.jbrunton.com
          USERNAME: deployer
          KEY: ${{ secrets.DEPLOYER_SSH_KEY }}
        with:
          script: |
            docker-compose up --detach --no-build --remove-orphans
