name: deploy

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'README.md'

env:
  CI: 1
  FORCE_COLOR: 1

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: docker login
        env:
          DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}
          DOCKER_USERNAME: jbrunton
        run: echo "$DOCKER_ACCESS_TOKEN" | docker login -u "$DOCKER_USERNAME" --password-stdin
  
      - name: build
        run: |
          docker-compose build
          docker-compose push

      - name: deploy
        uses: appleboy/ssh-action@master
        env:
          HOST: monitoring.jbrunton.com
          USERNAME: deployer
          KEY: ${{ secrets.DEPLOYER_SSH_KEY }}
          ALERTMANAGER_SLACK_API_URL: ${{ secrets.ALERTMANAGER_SLACK_API_URL }}
          ALERTMANAGER_OPSGENIE_API_KEY: ${{ secrets.ALERTMANAGER_OPSGENIE_API_KEY }}
        with:
          script: |
            export ALERTMANAGER_SLACK_API_URL
            export ALERTMANAGER_OPSGENIE_API_KEY

            cd app
            git pull

            cp .env.prod .env
            ./setup.sh

            export COMPOSE_FILE=docker-compose.yml
            docker-compose pull
            docker-compose up --detach --no-build --remove-orphans
            docker-compose restart
          envs: ALERTMANAGER_SLACK_API_URL,ALERTMANAGER_OPSGENIE_API_KEY
